name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: nix-enabled-runners
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/cachix-action@v15
        with:
          name: paolino
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix run --quiet .#cardano-ledger-read-tests

  code-quality:
    runs-on: nix-enabled-runners
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/cachix-action@v15
        with:
          name: paolino
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Check formatting
        run: |
          nix develop --quiet .#quality --command bash -c \
            "just format && git diff --exit-code"
      - name: Run hlint
        run: |
          nix develop --quiet .#quality --command just lint
